image: node:20

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - rm -rf public && mkdir public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main
